const LinkActionTypes = {
  ADD_LINK: "ADD_LINK",
  REMOVE_LINK: "REMOVE_LINK",
  UPDATE_LINKS: "UPDATE_LINKS",

  AUTH_LINKS_REQUEST: "AUTH_LINKS_REQUEST",
  AUTH_LINKS_SUCCESS: "AUTH_LINKS_SUCCESS",
  AUTH_LINKS_FAIL: "AUTH_LINKS_FAIL",
};

export default LinkActionTypes;
